### ISSUE TITLE
Please add PDF or other freely readible images of the board trace layouts

### ISSUE THREAD

**Issue by herrold** [sparkfun/CryptoCape#5]
The files currently offered require ownership and setup of a Eagle (proprietary) piece of software to effectively render a view.  Please add PDF or other graphical image forms not requiring such

(this issue arose doing IRC support)

**Comment by ToniCorinne** [comment]
I've added a PDF to the repo. Thanks for doing IRC support! 

A note for anyone that comes across this- there is a [Freeware version](http://www.cadsoftusa.com/download-eagle/freeware/) of Eagle available to allow users to open and view all of our design files.

**Comment by jbdatko** [comment]
Thanks @ToniCorinne !
